-- ===========================================
-- Framecast AI — Complete Database Schema
-- ===========================================
-- Run this entire script in Supabase SQL Editor
-- (Dashboard > SQL Editor > New Query > Paste > Run)
-- ===========================================


-- -------------------------------------------
-- 1. Extensions
-- -------------------------------------------

create extension if not exists "uuid-ossp";


-- -------------------------------------------
-- 2. Tables
-- -------------------------------------------

-- Credits: tracks how many credits each user has
create table public.credits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  credits bigint not null default 0,
  created_at timestamptz not null default now()
);

-- Models: AI training models created by users
create table public.models (
  id bigint generated by default as identity primary key,
  "modelId" text,
  name text,
  pack text,
  status text not null default 'processing',
  type text,
  user_id uuid references auth.users(id) on delete cascade,
  email_notified boolean not null default false,
  created_at timestamptz not null default now()
);

-- Samples: training images uploaded for a model
create table public.samples (
  id bigint generated by default as identity primary key,
  "modelId" bigint not null references public.models(id) on delete cascade,
  uri text not null,
  created_at timestamptz not null default now()
);

-- Images: generated headshot results
create table public.images (
  id bigint generated by default as identity primary key,
  "modelId" bigint not null references public.models(id) on delete cascade,
  uri text not null,
  created_at timestamptz not null default now()
);

-- AI Edited Images: images created with the Magic Editor
create table public.ai_edited_images (
  id uuid not null default uuid_generate_v4() primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  image_url text not null,
  original_image_url text,
  prompt text not null default '',
  mode text not null default 'generate',
  storage_path text not null,
  created_at timestamptz not null default now()
);

-- Payments: records of all payment transactions
create table public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric not null,
  currency text not null default 'usd',
  created_at timestamptz not null default now()
);

-- Email Templates: customizable transactional email templates
create table public.email_templates (
  id bigint generated by default as identity primary key,
  type text not null unique,
  subject text not null,
  html text not null default '',
  is_custom boolean not null default false,
  updated_at timestamptz not null default now()
);

-- Platform Config: application wide key value settings
create table public.platform_config (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null default '""'::jsonb,
  updated_at timestamptz not null default now()
);

ouser_id);

create policy "Users can insert own models"
  on public.models for insert
  with check (auth.uid() = user_id);

create policy "Users can update own models"
  on public.models for update
  using (auth.uid() = user_id);

create policy "Users can delete own models"
  on public.models for delete
  using (auth.uid() = user_id);

-- Samples: users can access samples belonging to their models
create policy "Users can read own samples"
  on public.samples for select
  using (
    exists (
      select 1 from public.models
      where models.id = samples."modelId"
        and models.user_id = auth.uide    select 1 from public.models
      where models.id = samples."modelId"
        and models.user_id = auth.uid()
    )
  );

create policy "Users can delete own samples"
  on public.samples for delete
  using (
    exists (
      select 1 from public.models
      where models.id = samples."modelId"
        and models.user_id = auth.uid()
    )
  );

-- Images: users can access images belonging to their models
create policy "Users can read own images"
  on public.images for select
  using (
    exists (
      select 1 from public.models
      where models.id = images."modelId"
        and models.user_id = auth.uid()
    )
  );

create policy "Users can insert own images"
  on public.images for insert
  with check (
    exists (
      select 1 from public.models
      where models.id = images."modelId"
        and models.user_id = auth.uid()
    )
  );

-- AI Edited Images: users can manage their own edited images
create policy "Users can read own ai_edited_images"
  on public.ai_edited_images for select
  using (auth.uid() = user_id);

create policy "Users can insert own ai_edited_images"
  on public.ai_edited_images for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own ai_edited_images"
  on public.ai_edited_images for delete
  using (auth.uid() = user_id);

-- Payments: users can view their own payments
create policy "Users can read own payments"
  on public.payments for select
  using (auth.uid() = user_id);

-- Email Templates: read only for authenticated users (admin writes via service role)
create policy "Authenticated users can read email templates"
  on public.email_templates for select
  using (auth.role() = 'authenticated');

-- Platform Config: read only for authenticated users (admin writes via service role)
create policy "Authenticated users can read platform config"
  on public.platform_config for select
  using (auth.role() = 'authenticated');


-- -------------------------------------------
-- 4. Functions
-- -------------------------------------------

-- Get a user email by their auth ID
create or replace function public.get_user_email_by_id(user_id_param uuid)
returns json
language plpgsql
security definer
as $$
declare
  result json;
begin
  select json_build_object('email', u.email)
  into result
  from auth.users u
  where u.id = user_id_param;

  return result;
end;
$$;

-- Get admin credits by their auth ID
create or replace function public.get_admin_credits_by_id(admin_id uuid)
returns bigint
language plpgsql
security definer
as $$
declare
  total bigint;
begin
  select coalesce(c.credits, 0)
  into total
  from public.credits c
  where c.user_id = admin_id;

  return coalesce(total, 0);
end;
$$;

-- Allocate credits to an admin user
create or replace function public.allocate_credits_to_admin(
  admin_id uuid,
  amount bigint,
  super_admin_id uuid
)
returns void
language plpgsql
security definer
as $$
begin
  insert into public.credits (user_id, credits)
  values (admin_id, amount)
  on conflict (user_id)
  do update set credits = credits.credits + amount;
end;
$$;

-- Queue a user for deletion (soft delete / anonymize)
create or replace function public.queuan
language plpgsql
security definer
as $$
declare
  target_uid uuid;
begin
  select id into target_uid
  from auth.users
  where email = target_email;

  if target_uid is null then
    return false;
  end if;

  -- Clean up all user data
  perform public.queue_user_for_deletion(target_uid);

  -- Remove from auth
  delete from auth.users where id = target_uid;

  return true;
end;
$$;

-- Hard delete user (alias)
create or replace function public.hard_delete_user(target_email text)
returns boolean
language plpgsql
security definer
as $$
begin
  return public.delete_user_completely(target_email);
end;
$$;

-- Nuclear hard delete: removes absolutely everything
create or replace function public.nuclear_hard_delete_user(target_email text)
returns boolean
language plpgsql
security definer
as $$
declare
  target_uid uuid;
begin
  select id into target_uid
  from auth.users
  where email = target_email;

  if target_uid is null then
    return false;
  end if;

  -- Remove all data
  delete from public.ai_edited_images where user_id = target_uid;
  delete from public.credits where user_id = target_uid;
  delete from public.payments where user_id = target_uid;
  delete from public.models where user_id = target_uid;

  -- Remove all auth identities and sessions
  delete from auth.identities where user_id = target_uid;
  delete from auth.sessions where user_id = target_uid;
  delete from auth.mfa_factors where user_id = target_uid;
  delete from auth.users where id = target_uid;

  return true;
end;
$$;

-- Process deletion queue: clean up anonymized users
create or replace function public.process_deletion_queue()
returns table(user_id uuid, anonymized_email text, deleted_at timestamptz)
language plpgsql
security definer
as $$
begin
  -- This returns any users that have already been cleaned up
  return query
    select u.id, u.email, u.deleted_at
    from auth.users u
    where u.deleted_at is not null;
end;
$$;

-- Cleanup anonymized users
create or replace function public.cleanup_anonymized_users()
returns table(user_id uuid, anonymized_email text, deleted_at timestamptz)
language plpgsql
security definer
as $$
begin
  return query
    select u.id, u.email, u.deleted_at
    from auth.users u
    where u.deleted_at is not null;
end;
$$;

-- Execute arbitrary SQL (admin only, use with caution)
create or replace function public.exec_sql(sql text)
returns void
language plpgsql
security definer
as $$
begin
  execute sql;
end;
$$;


-- -------------------------------------------
-- 5. Default Platform Configuration
-- -------------------------------------------

insert into public.platform_config (key, value) values
  ('credit_value', '0.1'::jsonb),
  ('profit_margin', '0.5'::jsonb),
  ('ai_model_api_cost', '1.5'::jsonb),
  ('ai_model_credits', '30'::jsonb),
  ('magic_editor_api_cost', '0.3'::jsonb),
  ('magic_editor_credits', '6'::jsonb),
  ('styles_pricing_mode', '"dynamic"'::jsonb),
  ('active_gemini_models', '["flash"]'::jsonb),
  ('primary_gemini_model', '"flash"'::jsonb),
  ('billing_packages', '[]'::jsonb),
  ('astria_test_mode', 'false'::jsonb)
on conflict (key) do nothing;


-- -------------------------------------------
-- 6. Storage Bucket (for Magic Editor images)
-- -------------------------------------------

insert into storage.buckets (id, name, public)
values ('ai-edited-images', 'ai-edited-images', true)
on conflict (id) do nothing;

-- Allow authenticated users to upload to their own folder
create policy "Users can upload own ai-edited-images"
  on storage.objects for insert
  with check (
    bucket_id = 'ai-edited-images'
    and auth.role() = 'authenticated'
  );

-- Allow authenticated users to read their own images
create policy "Users can read own ai-edited-images"
  on storage.objects for select
  using (
    bucket_id = 'ai-edited-images'
    and auth.role() = 'authenticated'
  );

-- Allow authenticated users to delete their own images
create policy "Users can delete own ai-edited-images"
  on storage.objects for delete
  using (
    bucket_id = 'ai-edited-images'
    and auth.role() = 'authenticated'
  );
