create extension if not exists "uuid-ossp";

create table if not exists public.video_jobs (
  id uuid not null default uuid_generate_v4() primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'queued',
  progress numeric not null default 0,
  input_json jsonb not null default '{}'::jsonb,
  output_json jsonb not null default '{}'::jsonb,
  error text,
  idempotency_key text,
  trigger_run_id text,
  engine_job_id text,
  required_credits bigint not null default 0,
  consumed_credits bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists video_jobs_user_id_idempotency_key_unique
  on public.video_jobs(user_id, idempotency_key)
  where idempotency_key is not null;

create table if not exists public.video_job_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.video_jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.video_jobs enable row level security;
alter table public.video_job_events enable row level security;

drop policy if exists "Users can read own video_jobs" on public.video_jobs;
create policy "Users can read own video_jobs"
  on public.video_jobs for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own video_jobs" on public.video_jobs;
create policy "Users can insert own video_jobs"
  on public.video_jobs for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own video_jobs" on public.video_jobs;
create policy "Users can update own video_jobs"
  on public.video_jobs for update
  using (auth.uid() = user_id);

drop policy if exists "Users can read own video_job_events" on public.video_job_events;
create policy "Users can read own video_job_events"
  on public.video_job_events for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own video_job_events" on public.video_job_events;
create policy "Users can insert own video_job_events"
  on public.video_job_events for insert
  with check (auth.uid() = user_id);

create table if not exists public.platform_config (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null default '""'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.platform_config (key, value)
values ('video_render_credits', '10'::jsonb)
on conflict (key) do nothing;

create or replace function public.create_video_job(
  p_user_id uuid,
  p_input_json jsonb,
  p_required_credits bigint,
  p_idempotency_key text default null
)
returns jsonb
language plpgsql
security definer
as $$
declare
  existing_job_id uuid;
  has_credits_table boolean;
  current_credits bigint;
  new_job_id uuid;
  effective_required_credits bigint;
begin
  if auth.uid() is null or auth.uid() <> p_user_id then
    raise exception 'UNAUTHORIZED';
  end if;

  if p_idempotency_key is not null then
    select id into existing_job_id
    from public.video_jobs
    where user_id = p_user_id and idempotency_key = p_idempotency_key
    limit 1;

    if existing_job_id is not null then
      return jsonb_build_object(
        'job_id', existing_job_id,
        'status', 'duplicate'
      );
    end if;
  end if;

  effective_required_credits := coalesce(p_required_credits, 0);
  has_credits_table := to_regclass('public.credits') is not null;
  if has_credits_table and effective_required_credits > 0 then
    select credits into current_credits
    from public.credits
    where user_id = p_user_id
    limit 1
    for update;

    current_credits := coalesce(current_credits, 0);
    if current_credits < effective_required_credits then
      raise exception 'INSUFFICIENT_CREDITS';
    end if;

    update public.credits
    set credits = credits - effective_required_credits
    where user_id = p_user_id;
  else
    effective_required_credits := 0;
  end if;

  new_job_id := uuid_generate_v4();
  insert into public.video_jobs(
    id,
    user_id,
    status,
    progress,
    input_json,
    required_credits,
    consumed_credits,
    idempotency_key
  )
  values (
    new_job_id,
    p_user_id,
    'queued',
    0,
    coalesce(p_input_json, '{}'::jsonb),
    effective_required_credits,
    effective_required_credits,
    p_idempotency_key
  );

  insert into public.video_job_events(job_id, user_id, event_type, payload)
  values (
    new_job_id,
    p_user_id,
    'queued',
    jsonb_build_object('required_credits', effective_required_credits)
  );

  return jsonb_build_object(
    'job_id', new_job_id,
    'status', 'queued'
  );
end;
$$;
